### ISSUE TITLE
Fix pixels on the left in the rendering code

### ISSUE THREAD

**Issue by leonidaspir** [loktar00/Javascript-Canvas-Terrain-Generator#3]
To fix this, change on index.js and line 206 the following:

```
    for(x = 0; x <= size; x += unitSize){
        for(y = 0; y <= size; y += unitSize){
```
to:

    for(x = 0; x < size - 1; x += unitSize){
        for(y = 0; y < size - 1; y += unitSize){

**Comment by loktar00** [comment]
Mind doing a PR? I mean I can just add this as well, but this is something I was meaning to fix forever and never got to it, lol granted it's not a huge amount of code, but you should get the credit regardless :P.

If you don't want to do a PR it's cool I can just commit it in.

**Comment by highvrahos** [comment]
Done!

Thanks for the great algorithm @loktar00 

Regards,

**Comment by loktar00** [comment]
Weird I never closed this, thanks for fixing the code!
