### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by Illya9999** [loktar00/Javascript-Canvas-Terrain-Generator#5]
Please add an ope source license to your project. As currently anyone who uses it is violating your copyright

**Comment by loktar00** [comment]
hah good idea, it used to be in the JS directly way back as MIT anyway I'll get one added thanks for the heads up!

**Comment by loktar00** [comment]
https://github.com/loktar00/Javascript-Canvas-Terrain-Generator/commit/1aff71691291459c708a20d4a8e9c4cbb736b8c4
